server:
  port: 8081 # 指定端口号
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sy?useSSL=false&serverTimezone=UTC
    username: root
    password: 20010629
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  data:
    redis:
      host: localhost
      port: 6379
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB # 单个文件的最大大小
      max-request-size: 100MB # 整个请求的最大大小
  kafka:
    enabled: true  # 启用 Kafka
    bootstrap-servers: 127.0.0.1:9092 # Kafka 服务器地址
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      enable-idempotence: true
      transactional-id-prefix: file-upload-tx-
      properties:
        client.dns.lookup: use_all_dns_ips
    consumer:
      group-id: file-processing-group # 消费者组 ID
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*" # 允许反序列化的包
        client.dns.lookup: use_all_dns_ips
    topic:
      file-processing: file-processing-topic1 # 新增的 Topic 配置
      dlt: file-processing-dlt # 死信队列主题
  webflux:
    client:
      max-in-memory-size: 16MB  # 增加响应大小限制
  codec:
    max-in-memory-size: 16MB    # 增加编解码大小限制


minio:
    endpoint: http://localhost:9000
    accessKey: minioadmin
    secretKey: minioadmin
    bucketName: uploads
    publicUrl: http://localhost:9000
jwt:
  secret-key: "PXrQbuCwXwOZzkML/Vm2S5rSwt1iybvmKtGDzVEu+Hc="

# 管理员账号初始化配置
admin:
  username: admin
  password: admin123
  primary-org: default
  org-tags: default,admin

file:
  parsing:
    chunk-size: 512 # 每个文本块的最大字符数

elasticsearch:
  host: localhost       # Elasticsearch主机地址
  port: 9200            # Elasticsearch端口号
  scheme: http          # 协议（http/https）

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.boot.autoconfigure.web.servlet: DEBUG
    org.springframework.security: DEBUG
    com.yizhaoqi.smartpai.service: DEBUG
    io.minio: DEBUG

log4j:
  logger:
    org:
      apache:
        tika=DEBUG:

deepseek:
  api:
    url: https://api.deepseek.com/v1
    key:
    # DeepSeek API Key

embedding:
  api:
    url: https://dashscope.aliyuncs.com/compatible-mode/v1
    key:    # 填入通义千问API key
    model: text-embedding-v4
    dimension: 2048  # 指定向量维度